import { createPdf } from './mod.ts';
import type { PDFDocumentDefinition } from './mod.ts';

// Data for our table
const tableBody = [
  [
    { text: 'Feature', style: 'tableHeader' },
    { text: 'Description', style: 'tableHeader' },
    { text: 'Example', style: 'tableHeader' },
  ],
  [
    'Page Setup',
    'Set page size and orientation. This document is A4 Portrait.',
    { text: 'pageSize: "A4", pageOrientation: "portrait"', alignment: 'left' }
  ],
  [
    'Text Wrapping & Alignment',
    'Long lines of text automatically wrap to fit their container. You can align text left, right, or center.',
    { text: 'This text is centered.', alignment: 'center' }
  ],
  [
    'Complex Tables',
    { text: 'Tables support dynamic widths, styling, and advanced cell content.', alignment: 'center', verticalAlignment: 'middle' },
    { text: 'widths: [100, "*", 150]', alignment: 'left' }
  ],
  [
    'Cell Alignment',
    'This cell demonstrates vertical and horizontal alignment within a table.',
    { text: 'Bottom-Right', alignment: 'right', verticalAlignment: 'bottom' }
  ],
  [
    'Multi-Page & Footers',
    'Content automatically flows to new pages. A footer can be replicated on each page with page numbers.',
    { text: 'Page {pageNumber} of {totalPages}', alignment: 'center' }
  ],
  ['Cell with a number', 123, null]
];


const docDefinition: PDFDocumentDefinition = {
  pageSize: 'A4',
  pageOrientation: 'portrait',
  margin: [40, 40, 40, 60],
  styles: {
    header: {
      fontSize: 24,
      bold: true,
      alignment: 'center',
      margin: [0, 0, 0, 20],
    },
    subheader: {
      fontSize: 18,
      bold: true,
      margin: [0, 10, 0, 5],
    },
    tableHeader: {
      bold: true,
      fontSize: 13,
      alignment: 'center',
    },
    times: {
        font: 'Times-Roman',
        italics: true,
    }
  },
  footer: {
    text: 'Page {pageNumber} of {totalPages} - Generated by Deno PDF Generator',
    alignment: 'center',
    fontSize: 10,
  },
  content: [
    {
      text: 'Deno PDF Generator - Feature Showcase',
      style: 'header',
    },
    {
      text: 'This document demonstrates all the major features of the Deno PDF Generator module. It includes examples of page setup, text formatting, complex tables, and footers.',
      margin: [0, 0, 0, 20],
    },
    {
        image: 'https://placehold.co/500x80.png',
    },
    {
      text: 'Feature Table',
      style: 'subheader',
    },
    {
      table: {
        widths: [100, '*', 150],
        body: tableBody,
      },
      fontSize: 12,
      layout: {
        fillColor: (rowIndex: number) => (rowIndex === 0) ? [0.85, 0.85, 0.85] : null,
        borderColor: [0.7, 0.7, 0.7],
        borderWidth: 0.5,
      }
    },
    {
        text: 'New Features on This Page',
        style: 'subheader',
        pageBreak: 'before',
    },
    {
        text: 'This text is in Times New Roman, italics.',
        style: 'times',
        margin: [0, 0, 0, 10],
    },
    {
        text: 'Unordered List:',
        bold: true,
    },
    {
        ul: [
            'Item 1',
            'Item 2',
            'A long list item that will definitely need to wrap to the next line to show how well the text wrapping works within list items.',
        ],
        margin: [0, 5, 0, 15]
    },
    {
        text: 'Ordered List:',
        bold: true,
    },
    {
        ol: [
            'First item',
            'Second item',
            'Third item',
        ]
    },
    {
        text: 'Full-Width Table (No Borders)',
        style: 'subheader',
    },
    {
      table: {
        widths: '*',
        body: [
          ['This column will be one-third of the page width', 'This column will also be one-third', 'And so will this one'],
          [{text: 'This is a test', italics: true}, 'Nothing special here', 'And nothing here either']
        ]
      }
    },
    {
        text: 'Auto-width Table with Styled Cells',
        style: 'subheader',
    },
    {
      table: {
        widths: ['auto', '*', 100, 'auto'],
        body: [
          [{text: 'Header 1', style: 'tableHeader'}, {text: 'Header 2', style: 'tableHeader'}, {text: 'Header 3', style: 'tableHeader'}, {text: 'Header 4', style: 'tableHeader'}],
          ['Short', 'This column will expand to fill the remaining space.', 'Fixed 100', {text: 'This cell is red', color: [1, 0, 0]}],
          [{text: 'A much longer text content', bold: true}, 'Another cell', '100', 'Short'],
          ['Medium', {text: 'This cell is blue and italic', color: [0, 0, 1], italics: true}, '100', 'A cell']
        ]
      },
      layout: {
        borderColor: [0.7, 0.7, 0.7],
        borderWidth: 0.5,
        fillColor: (rowIndex: number) => (rowIndex === 0) ? [0.85, 0.85, 0.85] : null,
      }
    }
  ],
};

async function generate() {
  const pdfBytes = await createPdf(docDefinition);
  await Deno.writeFile('showcase-example.pdf', pdfBytes as Uint8Array);
  console.log('Showcase PDF generated successfully!');
}

generate();
