import { createPdf } from './mod.ts';

// Data for our table
const tableBody = [
  [
    { text: 'Feature', style: 'tableHeader' },
    { text: 'Description', style: 'tableHeader' },
    { text: 'Example', style: 'tableHeader' },
  ],
  [
    'Page Setup',
    'Set page size and orientation. This document is A4 Portrait.',
    { text: 'pageSize: "A4", pageOrientation: "portrait"', alignment: 'left' }
  ],
  [
    'Text Wrapping & Alignment',
    'Long lines of text automatically wrap to fit their container. You can align text left, right, or center.',
    { text: 'This text is centered.', alignment: 'center' }
  ],
  [
    'Complex Tables',
    { text: 'Tables support dynamic widths, styling, and advanced cell content.', alignment: 'center', verticalAlignment: 'middle' },
    { text: 'widths: [100, "*", 150]', alignment: 'left' }
  ],
  [
    'Cell Alignment',
    'This cell demonstrates vertical and horizontal alignment within a table.',
    { text: 'Bottom-Right', alignment: 'right', verticalAlignment: 'bottom' }
  ],
  [
    'Multi-Page & Footers',
    'Content automatically flows to new pages. A footer can be replicated on each page with page numbers.',
    { text: 'Page {pageNumber} of {totalPages}', alignment: 'center' }
  ]
];

// Add more rows to test multi-page functionality
for (let i = 1; i <= 15; i++) {
    tableBody.push([`Row ${i}`, `Some content for row ${i}`, 'This is just to make the document longer.']);
}


const docDefinition = {
  pageSize: 'A4',
  pageOrientation: 'portrait',
  margin: [40, 10, 40, 60], // [left, top, right, bottom] - SMALL TOP MARGIN
  styles: {
    header: {
      fontSize: 24,
      bold: true,
      alignment: 'center',
      color: [0.1, 0.6, 0.9],
      margin: [0, 0, 0, 20],
    },
    subheader: {
      fontSize: 18,
      bold: true,
      margin: [0, 10, 0, 5],
    },
    tableHeader: {
      bold: true,
      fontSize: 13,
      color: [0, 0, 0],
      alignment: 'center',
    },
    fullWidthTable: {
        table: {
            widths: '*',
        }
    }
  },
  footer: {
    text: 'Page {pageNumber} of {totalPages} - Generated by Deno PDF Generator',
    alignment: 'center',
    fontSize: 10,
    color: [0.5, 0.5, 0.5],
  },
  content: [
    {
      text: 'Deno PDF Generator - Feature Showcase',
      style: 'header',
    },
    {
      text: 'This document demonstrates all the major features of the Deno PDF Generator module. It includes examples of page setup, text formatting, complex tables, and footers.',
      margin: [0, 0, 0, 20],
    },
    {
        image: 'https://placehold.co/500x80.png',
    },
    {
      text: 'Feature Table',
      style: 'subheader',
    },
    {
      style: 'fullWidthTable',
      table: {
        body: tableBody,
      },
      fontSize: 12,
      layout: {
        fillColor: (rowIndex: number) => (rowIndex === 0) ? [0.8, 0.8, 0.8] : null,
        borderColor: [0.7, 0.7, 0.7],
        borderWidth: 0.5,
      }
    },
  ],
};

async function generate() {
  // Get PDF as Uint8Array
  const pdfBytes = await createPdf(docDefinition);
  await Deno.writeFile('showcase-example.pdf', pdfBytes as Uint8Array);
  console.log('Showcase PDF generated successfully!');

  // Get PDF as base64 data URI
  const pdfBase64 = await createPdf(docDefinition, { output: 'base64' });
  // console.log('Base64 PDF:', pdfBase64);
}

generate();
